[build]
  command = "npm run build"
  publish = ".next"

[context.develop]
  command = "npm run build"
  [context.develop.environment]
    NEXT_PUBLIC_APP_ENV = "develop"

[[plugins]]
  package = "@netlify/plugin-nextjs"
